name: Build and publish Docker image

on:
  push:
    branches:
      - main
      - ci/*

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set lower case owner name
        run: echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64,linux/arm/v6,linux/arm64
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/budget-api:latest
            ghcr.io/${{ env.OWNER_LC }}/budget-api:${{ github.sha }}
          file: Dockerfile
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
